apiVersion: v1
kind: Service
metadata:
  annotations:
    config.kubernetes.io/origin: |
      path: ../../base/guestbook-svc.yaml
    deployment-branch: env/prod
    deployment-branch-url: https://github.com/kustomize-everything/guestbook-deploy/tree/env/prod
    deployment-repo: kustomize-everything/guestbook-deploy
    deployment-repo-url: https://github.com/kustomize-everything/guestbook-deploy
  labels:
    app.kubernetes.io/managed-by: kustomize-v4.5.3
  name: guestbook
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: guestbook
