apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
- guestbook-debug.yaml

patches:
- path: ingress-dev-patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: guestbook
    version: v1

