apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: ingress-patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: guestbook
    version: v1

images:
- name: ghcr.io/kustomize-everything/guestbook
  newTag: 00027-d0d1e6a
