name: Render Manifests
on:
  pull_request:
    branches:
      - main

jobs:
  render-manifests:
    name: Dry-run render manifests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, stage, prod]

    steps:
      - uses: actions/checkout@v3
        with:
          # fetch-depth: 0 needed to get all branches
          fetch-depth: 0
      - uses: kustomize-everything/action-env-build-and-deploy@highb-combined-diff-and-optional-deploy
        with:
          dry-run: true
          environment: ${{ matrix.env }}
          push-environment-regex: (dev|stage)
          pr-environment-regex: prod
